### ISSUE TITLE
DOS build using djgpp

### ISSUE THREAD

**Issue by alexander-zolkin** [silentbicycle/greatest#101]
I am trying to build a simple program with greatest under DOSBox using [djgpp](http://www.delorie.com/djgpp) and [this is what I am getting](https://sun9-19.userapi.com/c857224/v857224991/190da0/dMDl_kPenmA.jpg).

Is there a way to use greatest under DOS?

**Comment by silentbicycle** [comment]
I haven't tried on DOS, but in theory it should work -- I have built it for microcontrollers which didn't have an operating system at all.

Since you're getting a warning about missing `greatest_info`, make sure you're using `GREATEST_MAIN_DEFS()` properly. The macro expansion includes the `greatest_info` definition, along with lots of other `static` internal functions.
