### ISSUE TITLE
Automatic test detection

### ISSUE THREAD

**Issue by Overdrivr** [silentbicycle/greatest#44]
Would you be open to add automatic test detection to the next major version ?

Similarly to what Catch C++ test library does 
https://github.com/philsquared/Catch/blob/master/docs/tutorial.md

I like the simplicity of your library but not having to modify several files to add tests suites and tests would be a nice feature IMO

**Comment by silentbicycle** [comment]
I don't want to build that into the `greatest.h` header, because then it has to handle specific platform details, build tools, and so on. When it matters, it's not hard to automate, but the details end up being platform specific. I'm definitely fine with making a `contrib/` directory and putting scripts to do that kind of thing in there. (I'd also move `greenest` there.)

You could use a small awk/Python/Ruby/Lua/etc. script to search for "^TEST " and update a "test_FILE_tests.h" header, which has the `RUN_TESTS` lines, then include that.

Lately, I've written the `RUN_TEST(testname);` lines first, then passed them through a script that generates empty test functions with `SKIPm("TODO");`. Particularly with parametric tests, I prefer to be more explicit.

**Comment by silentbicycle** [comment]
Also, it's a design constraint of mine that greatest.h stay small and portable. Where catch is 10204 lines of C++, greatest is only 921 lines of C.

**Comment by Overdrivr** [comment]
OK I understand your opinion, if you have the feeling it cannot be done in a portable manner then I agree.

**Comment by silentbicycle** [comment]
I'm happy to include example scripts for this sort of thing (with the caveat about being platform-specific examples), and since greatest itself is pretty stable, that's a good thing to prioritize for the next release.
