### ISSUE TITLE
Compatibibility with Continuous Integration services 

### ISSUE THREAD

**Issue by Overdrivr** [silentbicycle/greatest#48]
Is greatest compatible with CI services like appveyor ?

I belive it would be compliant as long as test errors are outputed on stderr instead of stdout. Looking at the code, this is not the case for now isn't it ?

**Comment by jibsen** [comment]
I may be wrong, but I think many CI services expect xUnit style XML output in order to get fancy test result pages.

If you just want to run your unit tests as part of the build, then that works fine with greatest (success depends on the return value of the unit test).

As an example, I am using [this AppVeyor script](https://github.com/jibsen/brieflz/blob/d46c35cb23807707047f0bec9a3a59cb1bdb16fc/appveyor.yml) to run unit tests using greatest. If one of the builds fail, I can go into the console log and see the output from the unit test there.

**Comment by Overdrivr** [comment]
How can Appveyor know that the test passed or failed unless errors are outputed on `stderr` instead of `stdout` ?

@jibsen Could you try to make a minor modification (in a new branch) on your program to voluntarily make the test fail to see if Appveyor reports a failed build ? Because I have the feeling that despite the test will fail Appveyor will report build success.

**Comment by jibsen** [comment]
Sure, I pushed a branch that fails one of the unit tests (`pack_numbers`), the AppVeyor build is [here](https://ci.appveyor.com/project/jibsen/brieflz/build/1.1.0-25).

As you can see the builds are failing, and if you go into one of the builds and check the bottom of the log you can see that the `pack_numbers` test is failing.

**Comment by Overdrivr** [comment]
Ah yes you are right, the return code is enough. Awesome :) 
Thank you @jibsen

**Comment by silentbicycle** [comment]
For what it's worth, greatest prints almost all output to GREATEST_STDOUT, which can be defined to stderr. It only defaults to stdout: https://github.com/silentbicycle/greatest/blob/master/greatest.h#L110

The only thing that explicitly prints to stdout is the greatest_printf_cb callback, which is used by ASSERT_EQUAL_T, ASSERT_STR(N)_EQ, and ASSERT_MEM_EQ. This will be fixed, but requires a major version bump because it's a breaking API change. https://github.com/silentbicycle/greatest/issues/39
