### ISSUE TITLE
Test silently fails if a user function carries same name as a TEST function

### ISSUE THREAD

**Issue by Overdrivr** [silentbicycle/greatest#49]
I am not sure if this can be classified as an issue, but it can make the tests fail silently so it's not ideal either. I had this issue from a user contribution on one of my repos

If by inadvertance a user-defined function has the same name (but not necessarily the same signature) than a `TEST` function, it turns out the compilation doesn't fail, and during testing the test function calls itself recursively instead of calling the function once.

```
int update_float32(float f)
{
    // some dummy code
   return (int)f;
}

TEST update_float32()
{
  ASSERT_EQ(update_float32(0.2),0);
  PASS();
}
```

I do agree this is an unlikely scenario, but it did happen at least and took me a bit of time to figure out what was going on.

**Comment by silentbicycle** [comment]
Indeed. The documentation should be more explicit about TESTs and SUITEs just being functions, with all that entails. (I'm surprised you don't get a compiler warning/error for the above, since the TEST is defining a function with a duplicated name that returns an enum and has unconstrained arguments.)
