### ISSUE TITLE
why we need PASS(), FAIL(), or SKIP()?

### ISSUE THREAD

**Issue by Kiddinglife** [silentbicycle/greatest#76]
In your blog, you said:

> Of course, most of the actual testing code is in the test cases. Every test is a function with zero or more assertions, then a call to PASS(), FAIL(), or SKIP(). (There are variants that return a custom message,  PASSm(msg), FAILm(msg), and SKIPm(msg).)

you explained clear about how to use PASS(), FAIL(), or SKIP() but did not say it clear why we need them?

For example, if one assertion failed, PASS() here makes no senses on me. Assertion failing is enough to say something. So why we need PASS(), FAIL(), or SKIP()?

Thanks, 
regards.

**Comment by silentbicycle** [comment]
Test cases return an enum value -- failing assertions exit the test function by returning `GREATEST_TEST_RES_FAIL`. Ending a test with a macro such as `PASS()` is necessary because the function has to return something, and that makes it return `GREATEST_TEST_RES_PASS`.

**Comment by Kiddinglife** [comment]
I see. thanks.

**Comment by silentbicycle** [comment]
No problem. It probably wouldn't hurt if I added a line or two about that to the docs.

**Comment by stoeckley** [comment]
So if you write `FAIL()` does that mean the test will always return that it failed, regardless of whether the assertions passed or failed? Why would you explicitly write that a test failed or passed, aren't the assertions and test infrastructure supposed to determine if it passed or failed?

**Comment by silentbicycle** [comment]
Yes. _If execution reaches a `FAIL()`_, the test always fails (and `FAILm("some message")` also saves a custom message to print with the failure).

Sometimes it's clear to write a test where a `FAIL` is conditionally reached via `if`, `switch`, or other control flow, rather than a condition checked directly by `ASSERT`, `ASSERT_EQ_FMT`, and so on.

I've also seen some negative tests that were structured like ```
if (thing) {
    if (some_function()) {
        PASS();
    }
}
FAIL();
```, in other words, it failed unless the specific code path that led to the `PASS()` was reached.

**Comment by stoeckley** [comment]
Thanks! Your explanations here and in #94 have cleared it up.

**Comment by silentbicycle** [comment]
Great. I'll rework that part of the README to explain them better in the next release -- a couple people have asked questions about them lately.
