### ISSUE TITLE
Feature: Different Test-Runner (exe) files

### ISSUE THREAD

**Issue by Taneeda** [silentbicycle/greatest#83]
Hi there,

I use the framework a lot at work to test my embedded code and I like the simplicity.

At my current project I have a lot of unit tests (currently ~1000) within different libraries. Unfortunately, due to the fact how the different libraries are integrated into the whole project, this leads to some problems at the execution order of the unit tests.

For Example:
- LibA calls LibB and LibC to initialze them
- I want to unit test all three different libs, but the dependencies result in problems for example when each lib will be initialized
- When I init LibB or LibC within the unit test, this results in a problem on execution in LibA, because the lib expects LibB and LibC as not initialized at startup

So, for the moment I am implementing functions only for unit tests to reset internal information to avoid such problem, which works for the moment but only because of very limited dependencies. I expect more such problems for the future when the count and complexity of the libs increase.

Is there or are there any plans for feature within the GREATEST framework to support different test runner (exe) to be executed? This would be the ideal solution for me, to differ the unit tests of the different libraries into separated test runner!?

Another benefit of such a feature is that it will be possible to test the same lib within different test runner to simulate different execution paths, which is necessary when internal static variabled must be reset before the next test...

Please let me know whether or how I can help (testing the framework, ...)...

Greetings,
Ronald

**Comment by silentbicycle** [comment]
Glad you like it! While I may be misunderstanding your use case, you may be able to set things up as you want using name-based filtering:

Rather than having one test runner that runs all tests (including tests which affect static state accessed by later tests), you could have the test runner only run one test each time, according to the `-s <suite>` and `-t <test>` name filter strings. (Note that these currently match on substrings, not the exact name -- I'm considering adding an exact-matches-only flag in a later release.) Then, you start the command line runner with different test name arguments each time. A list for this could be auto-generated by using the `-l` / `greatest_list_only()` flag to print the test names.

If the command line runner doesn't fit so well with your project setup (especially if you're using some sort of embedded IDE), you can also use function calls instead -- see the "Running Tests In Another Program" section in the README and `example_no_runner.c` in the repo. This makes much of the remaining text setup more flexible -- the command line runner tries to provide a reasonable default setup, but it isn't required.

If you're on a Unix-y OS (I suspect you may not be, but you didn't say), you could also run each test on a forked child process and have the parent wait for a pass/fail/skip message (or process termination) before proceeding. Because of copy-on-write, any static variables will only be modified in the child, and subsequent tests will be unaffected. (This isn't included in greatest for portability reasons, though a future version may have it as a separate extension.) There may be something comparable available on Windows, but I'm not very familiar with the OS APIs.

Finally, shuffling test order can help detect unexpected test interactions due to initializing static state -- see "Random Shuffling".

**Comment by Taneeda** [comment]
Hi, sorry for the late answer, unfortunately I didn't had the time to check these options in detail...

In summary, what I need is an easy way to reset the "static" variables within the production code, which I want to test within the unit tests. So, this is why I asked for separated test runner executable.

From you options, the "Running Tests In Another Program" ability sound like what I need. At the moment, I try to play with the abilities to see, whether is works for me...

**Comment by silentbicycle** [comment]
Right, that alone isn't going to reset the static variables. You need to run each test in its own address space, so that the statically initialized variables are fresh each time. You could:

1. Use a script to call the test runner once for each test. You could generate the test list by scraping the output from `-l`. This is probably the easier option.

2. Restructure your test code so each unit test is in its own `.c` file with a `main` that does the `greatest` setup and runs the test:

    /* other includes, etc. go here */
    #include "greatest.h"

    GREATEST_MAIN_DEFS();

    int main(int argc, char **argv) {
        GREATEST_MAIN_BEGIN();      /* command-line options, initialization. */
        RUN_TEST(some_test);        /* just run one test */
        GREATEST_MAIN_END();        /* display results */
    }

and then you don't need to bother with command line arguments to limit which test runs.

3. Wrap each test in something that `fork()`s a child process, runs the test's verification steps in that process (and only modifies its own copies of the static variables), and then sends the test result to the parent. greatest doesn't include code to do this because it's not portable (an implementation for Unix would be completely different from on Windows), but I might add an extension with code to do it on Unix under `contrib/` in a future release. 

4. Write a cleanup function that resets all the static variables, and then use that as a `SETUP` hook. In an embedded context that's probably more work than the other options (there's likely to be a lot of static state in several compilation units, so each would need a `MODULE_reset()` function)). It's worth considering if there are only a few variables, though.

**Comment by Taneeda** [comment]
👍 

At the moment, I'm already doing something as you mentioned in option 4, to reset the internals for the following tests, which is ok to me because in fact I don't have much problem with running all the SUITE/TEST(s) in on runner, just in some cases which are easy to handle...

For the future, I decided to create a simple application to execute the SUITE's in a single execution. In principle, this is what you supposed in option 1.

I refactored my initial script (created at work) and committed the current state to [GUTR](https://github.com/Taneeda/gutr) (GREATEST Unit-Test Runner) on my profile. Please let me know your thoughts, contructive feedback would be great.

**Comment by silentbicycle** [comment]
If you've got a test runner with just one test, you don't need to use SUITEs at all - `main` can just call `RUN_TEST` directly. I usually use suites to group tests with related setup and test targets, but they're entirely optional.

For resetting static state, one convention I've used is putting everything static in a file in a single struct (`struct MODULENAME_state { ... }`), so the reset function can just memset that and then re-init any non-zeroed fields. That isn't an option when using things like third party embedded drivers, but is convenient when it's possible.

Running each test or suite in a separate program can also be useful to speed up the overall test run - using different processes can benefit from multiple cores.

GUTR looks like it fits your use case well. Being able to toggle Single Runner Execution can help find tests where state isn't being fully reset. (Test shuffling can also help find tests that don't properly clean up, but assumes everything is in the same test runner.) I don't have a Windows-based development environment handy right now, so I can't really evaluate it further.

Also, I posted a new version of greatest with a couple bug fixes and documentation improvements, and I will probably be posting 1.5.0 with a few new features later this week. There will be a new switch to run tests whose name _exactly_ matches the `-t` argument, rather than treating it as a substring match. That might help with GUTR.
