### ISSUE TITLE
something about #define

### ISSUE THREAD

**Issue by torchlegend** [silentbicycle/greatest#92]
i m a newer.i have read the greatest.h,there is something that i dont understand.There are lines like  #define PASS           GREATEST_PASS
#define GREATEST_PASS() GREATEST_PASSm(NULL)
in that why don't #define PASS() GREATEST_PASSm(NULL)?
is there something important or define for a certain purpose?

**Comment by silentbicycle** [comment]
It happens in two layers because they serve different purposes:

`#define`ing `PASS` to `GREATEST_PASS` is in a block near the end, which `#define`s a bunch of aliases. It's convenient to use `SUITE`, `PASS`, `ASSERT`, etc. rather than prefixing everything with `GREATEST_`, but those aliases can be turned off (by `#define`ing `GREATEST_USE_ABBREVS` to `0`) in case another library also provides something called `PASS`, `ASSERT`, or whatever. I don't want the name conflict to break someone's project.

The `#define` for `GREATEST_PASS()` is making it equivalent to `GREATEST_PASSm(NULL)` -- it's like calling `GREATEST_PASSm` with a default argument of NULL. That argument is used for setting a custom message. I don't think `PASSm` gets used a lot, but it's helpful to say something like `FAILm("not found")`, rather than just `FAIL()`, because that message appears in the test runner's failure details.

**Comment by torchlegend** [comment]
Thanks for your detailed answer.To be honest,i haven't expected your answer so soon.Thank you very much.
