### ISSUE TITLE
Don't know how you skip?

### ISSUE THREAD

**Issue by torchlegend** [silentbicycle/greatest#94]
https://github.com/silentbicycle/greatest/blob/7f89ba4c5fdb5c6b776d5d8e4dcb17cb77cbe789/example.c#L17-L25
I run the very first part of the code in example.c,and I got results like this:
s
Total: 1 test (0 ticks, 0.000 sec), 1 assertion
Pass: 0, fail: 0, skip: 1.

But skip() only equals to #define GREATEST_SKIPm(MSG) , in that I don't know how you achieve skip by using       greatest_info.msg = MSG;  and    return GREATEST_TEST_RES_SKIP;
I am really confused,how you achieve this?
Thanks,
regards.

**Comment by silentbicycle** [comment]
I'm not sure I understand your question, but -- `SKIP()` is an alias for `GREATEST_SKIP()`, which expands to `GREATEST_SKIPm(NULL)`. This skips the rest of the test, but doesn't set any message.

You can skip with a message by using something like `SKIPm("test doesn't make sense with this config");`. The skip messages don't print with the default verbosity level, but will print with `-v` or if `greatest_set_verbosity` is used with a level > 0.

Does that help?

**Comment by silentbicycle** [comment]
If your question is about why that causes it to skip the rest of the test, it's because test cases return a PASS/SKIP/FAIL enum, and the various `PASS`/`FAIL`/`SKIP`/`ASSERT` functions expand to returning one of those, possibly after checking a condition. That's why calls to sub-functions which use `ASSERT`s need to be wrapped in `CHECK_CALL`.

**Comment by torchlegend** [comment]
Yes,my question is about why that causes it to skip the rest of the test,since test cases return a PASS/SKIP/FAIL enum,for example return a SKIP enum，then how it skip the rest of the test?Is there any code related to skip?Is this function included in GREATEST_MAIN_DEFS()?

**Comment by torchlegend** [comment]
> If your question is about why that causes it to skip the rest of the test, it's because test cases return a PASS/SKIP/FAIL enum, and the various `PASS`/`FAIL`/`SKIP`/`ASSERT` functions expand to returning one of those, possibly after checking a condition. That's why calls to sub-functions which use `ASSERT`s need to be wrapped in `CHECK_CALL`.

Yes,my question is about why that causes it to skip the rest of the test,since test cases return a PASS/SKIP/FAIL enum,for example return a SKIP enum，then how it skip the rest of the test?Is there any code related to skip?Is this function included in GREATEST_MAIN_DEFS()?

**Comment by silentbicycle** [comment]
> Is this function included in `GREATEST_MAIN_DEFS()`?
Yes -- search for `GREATEST_TEST_RES_SKIP` (the enum value returned by `SKIP()`) and follow back from where the code checks for it.

The overall control flow isn't very complicated (particularly compared to, say, a test system that uses `setjmp`/`longjmp`), the macros are just trying to eliminate a lot of boilerplate and tedious details.

**Comment by torchlegend** [comment]
> > Is this function included in `GREATEST_MAIN_DEFS()`?
> 
> Yes -- search for `GREATEST_TEST_RES_SKIP` (the enum value returned by `SKIP()`) and follow back from where the code checks for it.
> 
> The overall control flow isn't very complicated (particularly compared to, say, a test system that uses `setjmp`/`longjmp`), the macros are just trying to eliminate a lot of boilerplate and tedious details.

Got it.Is this function name :   static void greatest_do_skip(void)?

**Comment by silentbicycle** [comment]
That's where it prints the message and updates the skip counter, yes.

I still don't really understand the rest of your question? The reason it skips the rest of the test is because `SKIP()` expands to `return GREATEST_TEST_RES_SKIP;` (among other things), and the `return` causes control flow to exit the test case function early.

There's a bit more code so it can print a custom message along the way, and it counts how many tests have been skipped, but there's really nothing more to it.

**Comment by torchlegend** [comment]
> That's where it prints the message and updates the skip counter, yes.
> 
> I still don't really understand the rest of your question? The reason it skips the rest of the test is because `SKIP()` expands to `return GREATEST_TEST_RES_SKIP;` (among other things), and the `return` causes control flow to exit the test case function early.
> 
> There's a bit more code so it can print a custom message along the way, and it counts how many tests have been skipped, but there's really nothing more to it.

I understood.It is a really easy question.When program return 1/-1,program end,then skip the rest of the test....My question ends.Really saddddddddddddd.

**Comment by torchlegend** [comment]
Thanks for your reply.I should learn more about C.

**Comment by stoeckley** [comment]
After reading the blog post, the Readme, and a couple issues, such as this one, I must admit I still don't understand what skip actually does, or how the pass/skip/fail functions are supposed to be used. Why would you write a test but choose to skip all the lines in the test after a certain point (i.e. return early)? Or are they only skipped in certain circumstances?

**Comment by silentbicycle** [comment]
Some circumstances where I'd use SKIP:
- A test that is only valid when run in certain environments, such as only on a 32 or 64-bit platform, or when code being tested was built with certain options.
- A parametric test (i.e., one run with `RUN_TESTp`) where the parameters are coming out of nested loops, and certain combinations don't make sense.
- A test that hasn't been written yet, but exists as a placeholder, with a name describing something that needs to be checked. In other words, using the test cases as a sort of TODO list. I do this quite often.

The other important difference is that `FAIL` (or `ASSERT`, etc.) failing will cause the test runner program to exit with a non-zero status (and thus could be used to halt a build in CI), whereas `SKIP`'d tests don't change the exit status. They also print differently (`s` rather than `.`) as a visual indication, and are counted separately.

Does that help? The section about `PASS`, `FAIL`, and `SKIP` in the README could use a bit more detail about how their behavior differs, so I'll add that in the next release.
