### ISSUE TITLE
Parameterizing a test function -- use TEST or just return enum?

### ISSUE THREAD

**Issue by stoeckley** [silentbicycle/greatest#96]
If I want to parameterize a test function, I know that I must call it with `CHECK_CALL()` but am wondering if it is fine for that function, which accepts arguments, to be a `TEST` or rather just explicitly return the greatest enum, or does this not matter?

**Comment by silentbicycle** [comment]
I'm not sure I understand your question -- I think you're asking about using `CHECK_CALL`, but you also mention parameterized tests, and they aren't that related.

First, in case it's helpful: looking at `example.c`, there's a parametric / parameterized test, that is, a test with arguments: 
```
TEST parametric_example_c99(int arg) {
    ASSERT(arg > 10);
    PASS();
}
```

This is called with `RUN_TESTp(parametric_example_c99, 10);`. It's inside a guard for C99, because the `RUN_TESTp` macro uses `__VA_ARGS__`, added in C99. If you're running in a pre-C99 standard, there's also `RUN_TEST1(test_case, &struct_with_args_for_test);`, which just passes in a single void pointer.

Otherwise, it sounds like you _might_ be asking about calling sub-functions with `CHECK_CALL`, which isn't really related to parameterized tests. For any function called with `CHECK_CALL`, it should return `enum greatest_test_res`, but the `CHECK_CALL` macro doesn't care what arguments are passed to the function -- all it does is check the return value, and if it isn't `GREATEST_TEST_RES_PASS`, then it returns it as the overall test result.

Does that help? If not, could you clarify your question?

**Comment by stoeckley** [comment]
I think of them as related since I would prefer to encapsulate the logic for a parametric test, i.e. by generating the inputs in a loop, inside another function rather than have that logic "global" in the suite itself. Thus I think these must be nested `TEST` methods, and thus I'd have to use `CHECK_CALL`. 

So I guess the question is if this nested parameterized `TEST` function that is called with `CHECK_CALL` can be defined as a `TEST` or if it must instead explicitly return `enum greatest_test_res` and *not* be defined as `TEST`.

**Comment by silentbicycle** [comment]
From an implementation standpoint, if you nest test cases and use `CHECK_CALL`, greatest will only see it as a single test case. I prefer to put the looping in the suite, because then I can use the name-based filtering to only run the tests with certain arguments sometimes (I use the name-based filtering a lot during development), but greatest will work either way. If you want to call multiple TEST functions with arguments from inside a single test case (called directly by `RUN_TEST` or one of its variants), then `CHECK_CALL` would be the right approach.

`TEST` is just an alias for `GREATEST_TEST`, which expands to `static enum greatest_test_res`; it's not doing anything sophisticated behind the scenes. `TEST` mostly exists for convenience, and so if I change the return type of test cases later it won't _necessarily_ be a breaking change for the API.

**Comment by stoeckley** [comment]
I'm not actually using `RUN_TEST` inside the nested call, I'm just doing this:

```
TEST another_test(sometype foo, sometype bar) {
  ASSERT(something(foo,bar));
  PASS();
}

TEST one(void) {
  sometype foo, bar;
  CHECK_CALL(another_test(foo, bar)); // perhaps inside a loop here
  PASS();
}
```
Is that adequate?

**Comment by silentbicycle** [comment]
Yes, and you'd just use `RUN_TEST` to call the outer function. Nesting calls to `RUN_TEST` won't work, because it updates what test is currently running in a global struct, and assumes there's no nesting.

**Comment by silentbicycle** [comment]
I suppose `RUN_TEST` _should_ explicitly error if called from inside another running test; currently, I think it'll just lead to strange errors.

**Comment by silentbicycle** [comment]
If this answers your question, then all there's left to do is see if the documentation could explain this better.

**Comment by stoeckley** [comment]
Thanks, sounds good.
